name: validate

on:
  push:
  pull_request:

concurrency:
  group: validate-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Check README.md
        run: |
          python3 validate.py --check
